<?xml version="1.0" encoding="utf-8"?><Database Name="MyFirstDB" Class="Images3DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=MyFirstDB;Integrated Security=True" SettingsObjectName="Homework_59.CL.Properties.Settings" SettingsPropertyName="MyFirstDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Images3" Member="Images">
    <Type Name="Images">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LikeCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>